// <auto-generated />
namespace Recurrence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedRequiredFields : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204131654144_AddedRequiredFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5dF3XhGM+lsYfpcdlkREir/Py/D2x2nkIrD6y/VGPp4RZe/3mepVzr5999J1q4jegJr9Xfh18QB+9rKtVXrfXr/Jz99rZ7KP0bvjq3e679s3wNfT/2Udny/be3kfpi3VZZpOSPjjPyib/KF19+uh1W9X55/kyr7M2n73M2javaWLOZjnjr3R4tPr0dqR4eHdnD6S4my2XVZu1NMs93DuYfneeLw2iTwmJNzShX56fN3kbwXgzqC/ydl7ZUb9ua+K+j9Jnxbt89jxfXrRzC+eL7J35hH79KP1qWRCz0kttvc7fu9/T5WxVFcv2h9/za6LxuvnJrMS7myd7M6BjmvjFqm3eB8rju47J+6xPwthmBTGW9kBzm73KV1VTEMtdd0RBXnmdt459CRUHXqRyDBmKomA7cyJ/V2Te6Ia7A8rh8RfZakWz5SkL/SR9LZriZPv1+6uDhcC4O20iWsFia3sikmQXeedb6powfVbUTQviTTJMwMls0Wt2O9KazjwKd9WPI7hpjN/lhZ7CHPc0GsPQN5/RgBakRHhsOjJCIqIH9b3X06zM6rgaO6nK9WK5QSFugiEKxgchn9wegtErPgzz2e2hOC3hw3Gf3h5SIPU+sOCL28Nzwu8Dc5/2IT2+25nmLid5qkFbdgxYly03CXW3ie3dCndHiB+rQN3sBvQkTJp8lBKJLosZpOv1dUOEGKPB+PUvKk/KIsd0mQZfZMviPG/aN9XbHC4NKYCv70pY+9k0s/L/tf4Es+uNnsN7WiDfD5gRSDh21TfhBywvs3o6z+qtRfbuznvD6tr2D4MWsdcM+z3BdK31zTDez1b37c6ATfF4ccBaizzRlE4qwlbwE+v+Ne14X7Qf3/XjgMdP86a4cCAQFSzzKVxRB9S0OVueV4a2NBwfI9Okz1sZsWd2XLfFeTZt6etp3jTs7/G8EsssJvnsbPnlul2t2+OmyReT8tof7+O7m/tnZyXE+fGXK/zl6bKvPwRCs4CEfbl8si7KmcX7WYRtBkCAQVT2CSvydwncxbWF9KJa3hKQku9pvsqX0BxviK9LAtZ8uXydXebDuN1Mw5Bij58W2UWdLXwKyidGNDPq2euCOvDfcP3Rn8SuFIQe/T8BAAD//7LVAvT5DgAA"; }
        }
    }
}
