// <auto-generated />
namespace Recurrence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204131611364_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5dF3XhGM+lsYfpcdlkREir/Py/D2x2nkIrD6y/TEui1WZv3tzvcq5288++qouPkrv+m1OCfv22mvynWriA6Emv1d+HXxAH72sq1Vet9ev8nP32tkshE3t7nbftW+Gr6H/zz46W7b39j5KX6zLMpuU9MF5Vjb5R+nq00ev26rOP8+XeZ21+exl1rZ5TZN3NssZf6XVo9WntyPXw7s7eyDX3Wy5rNqsJU7o4d7B9LvzfGkQfUpIvKFJ//L8vMnbCMabQX2Rt/PKjvp1WxOHfpQ+K97ls+f58qKdWzhfZO/MJ/TrR+lXy4IYml5q63Xu9yt/b+72dDlbVcWytR0Tk42ZI94T/2Oi/mLVNjfNW8Bodx2n9fmPpKbNCppd7YEInL3KV1VT0Lxfd/hRXnmdt46HCBUHXkcGRo6iYDtzsnlXhNMI8d0BKX78RbZa0WR5Uq2fpK9FpE+2X7+/3C4Ext1pE4hvB1vbE5Eku8g731LXhOmzom5aEG+SYQJOZotes9uR1nTmUbirAxzBTWP8Li/0NNu4p1YYhr75jAa0IEnmsenICImIMtL3Xk+zMqvjuuSkKteL5QattAmGSLkPQj65PQQj3D4M89ntoTgR8+G4T/uQHt/tELM7X54AasuOru5O/ibR6TaxvVsR6ojKY2Xbm61ij4+lyUcpkeiymIGHX183RIgxGoxf/6LypCxyqDXT4ItsWZznTfumepvDwpOYfX3Lak1F08zKiHz+v8N0slq/0Ui+p573Td6MQMLPqb4Jk7e8zOrpPKu3Ftm7O+9rxrrWh4f+Ddqevh690fwMWR/hXCLepCJsBT+xVl/TLvWF6PFd3wF9/DRvigsHAu7oMp/Cv3FATZuz5XllaEvD8TEyTfqzmBEjZMd1W5xn05a+nuZNw+7LT2blmpqcLib57Gz55bpdrdvjpskXk/LaH+/ju5v7Z+Mb4vz4yxX+8rTG1x8CoVmAl79cPlkX5czi/SzCNgMgwCAqZYQVuW8E7uLaQnpRLW8JSMn3NF/lS8joG+LrkoA1Xy5fZ5f5MG430zCk2OOnRXZRZwufgvKJYvI6Q6TguqAO/Ddcf/QnsStFP0f/TwAAAP//0YZeDXINAAA="; }
        }
    }
}
