// <auto-generated />
namespace Recurrence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class Initial : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204131628445_Initial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5dF3XhGM+lsYfpcdlkREir/Py/D2x2nkIrD6y/VGPp4RZe/3mepVzr5999J1q4jegJr9Xfh18QB+9rKtVXrfXr/Jz99rZ7KP0bvjq3e679s3wNfT/2Udny/be3kfpi3VZZpOSPjjPyib/KF19+uh1W9X55/kyr7M2n73M2javaWLOZjnjr3R4tPr0dqR4eHdnD6S4my2XVZu1NMs93DuYfneeLw2iTwmJNzShX56fN3kbwXgzqC/ydl7ZUb9ua+K+j9Jnxbt89jxfXrRzC+eL7J35hH79KP1qWRCz0kttvc79fuXvzd2eLmerqli2P/SOj2m2Fqu2uWmefSiP7zrO7PMrSVCbFcQN2gNNSPYqX1VNQXxy3eFfeeV13jqeI1QceBGlMRg/ioLtzMnpXRFUI9B3ByT68RfZakU09iRcP0lfi3ifbL9+fxleCIy70yYiyhZb2xORJLvIO99S14Tps6JuWhBvkmECTmaLXrPbkdZ05lG4qzMcwU1j/C4v9LTcuKeGGIa++YwGtCDJ57HpyAiJiPLS915PszKr47rnpCrXi+UGLbYJhmgFH4R8cnsIRhn4MMxnt4fiZNuH4z69PSQnrD4k92kf0uO7nWnpzrwnytqyYyW6bLRJCLtNbO9WGDtC91gF4GZb25MIafJRSiS6LGaQhtfXDRFijAbj17+oPCmLHOQ1Db7IlsV53rRvqrc5/AYS2K9vr62RappZ+f9ao83sdaN5fk8L6RvbGYGE91R9E8Z2eZnV03lWby2yd3fe1451DegHAesaRYb7DZrEvnofUN0eCw0YRREDmolJRdgKfmJEv6a57Evk47u+j/z4ad4UFw4EPOZlPoWb5oCaNmfL88rQlobjY2Sa9FkiI67Kjuu2OM+mLX09zZuGnaGfzMo1pnoxyWdnyy/X7WrdHjdNvpiU1/54H9/d3D/7BCHOj79c4S9PBX39IRCaBQTjy+WTdVHOLN7PImwzAAIMoiJLWJEzSOAuri2kF9XyloCUfE/zVb6EwL8hvi4JWPPl8nV2mQ/jdjMNQ4o9flpkF3W28CkonygmrzPq2euCOvDfcP3Rn8SuFKAd/T8BAAD//wHysAgVDgAA"; }
        }
    }
}
