// <auto-generated />
namespace Recurrence.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddedEnumWorkAround : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204131643041_AddedEnumWorkAround"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so1f5dF3XhGM+lsYfpcdlkREir/Py/D2x2nkIrD6y/VGPp4RZe/3mepVzr5999J1q4jegJr9Xfh18QB+9rKtVXrfXr/Jz99rZ7KP0bvjq3e679s3wNfT/2Udny/be3kfpi3VZZpOSPjjPyib/KF19+uh1W9X55/kyr7M2n73M2javaWLOZjnjr3R4tPr0dqR4eHdnD6S4my2XVZu1NMs93DuYfneeLw2iTwmJNzShX56fN3kbwXgzqC/ydl7ZUb9ua+K+j9Jnxbt89jxfXrRzC+eL7J35hH79KP1qWRCz0kttvc79fuXvzd2eLmerqli2P/SOXxOF181PZiWabp7qzYCOadoXq7Z5HyiP7zoW7zM+iWKbFcRW2gPNbPYqX1VNQQx33REEeeV13jrmJVQceJHJMSQoioLtzAn8XZF4oxnuDqiGx19kqxVNlqcq9JP0teiJk+3X768MFgLj7rSJ6ASLre2JSJJd5J1vqWvC9FlRNy2IN8kwASezRa/Z7UhrOvMo3FU+juCmMX6XF3rqctzTZwxD33xGA1qQCuGx6cgIiYgW1PdeT7Myq+NK7KQq14vlBnW4CYaoFx+EfHJ7CEar+DDMZ7eH4pSED8d9entIgdT7wIIvbg/PCb8PzH3ah/T4bmeau5zkqQZt2TFfXbbcJNTdJrZ3K9wdIX6sAnWzE9CTMGnyUUokuixmkK7X1w0RYowG49e/qDwpixzTZRp8kS2L87xp31Rvczg0pAC+viNhrWfTzMr/13oTzK43+g3vaYF8L2BGIOHWVd+EF7C8zOrpPKu3Ftm7O+9rYLuW/YOARaw1g37P4XVt9c0w3s9S963OgEXxOHHAVos00YROKsJW8BPb/jWteF+wH9/1Y4DHT/OmuHAgEBEs8yncUAfUtDlbnleGtjQcHyPTpM9ZGTFndly3xXk2benrad407OzxvBLHLCb57Gz55bpdrdvjpskXk/LaH+/ju5v7Z1clxPnxlyv85Wmyrz8EQrOAfH25fLIuypnF+1mEbQZAgEFU8gkrcnYJ3MW1hfSiWt4SkJLvab7Kl9Abb4ivSwLWfLl8nV3mw7jdTMOQYo+fFtlFnS18CsonRjQz6tnrgjrw33D90Z/ErhSAHv0/AQAA//+AtWj29Q4AAA=="; }
        }
    }
}
